services:
  pretix:
    image: 'pretix/standalone:stable'
    depends_on:
      - db
      - redis
    environment:
      # format is PRETIX_${section}_${key} from config
      PRETIX_PRETIX_URL: '${PRETIX_PRETIX_URL}'
      PRETIX_PRETIX_CURRENCY: 'EUR'
      PRETIX_LOCALE_DEFAULT: 'de'
      PRETIX_LOCALE_TIMEZONE: 'Europe/Berlin'
      PRETIX_DATABASE_BACKEND: 'postgresql'
      PRETIX_DATABASE_HOST: 'db'
      PRETIX_DATABASE_NAME: 'pretix'
      PRETIX_DATABASE_USER: 'pretix'
      PRETIX_DATABASE_PASSWORD: '${PRETIX_DATABASE_PASSWORD}'
      PRETIX_REDIS_LOCATION: 'redis://redis/0'
      PRETIX_REDIS_SESSIONS: 'true'
      PRETIX_CELERY_BROKER: 'redis://redis/1'
      PRETIX_CELERY_BACKEND: 'redis://redis/2'
      PRETIX_PRETIX_TRUST_X_FORWARDED_FOR: 'true'
      PRETIX_PRETIX_TRUST_X_FORWARDED_PROTO: 'true'
      PRETIX_PRETIX_TRUST_X_FORWARDED_HOST: 'true'
      PRETIX_PRETIX_DATADIR: '/data'
      PRETIX_MAIL_HOST: 'smtp-relay.gmail.com'
      PRETIX_MAIL_PORT: '587'
      PRETIX_MAIL_FROM: 'kontakt@youngvision.org'
      PRETIX_MAIL_PASSWORD: '${PRETIX_MAIL_PASSWORD}'
      PRETIX_MAIL_TLS: 'on'
      PRETIX_MAIL_ADMINS: 'it@youngvision.org'
    volumes:
      - 'pretix-data:/data'
    healthcheck:
      test: 'wget --spider localhost/healthcheck/ || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db:
    image: 'postgres:16'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: '${PRETIX_DATABASE_PASSWORD}'
      POSTGRES_USER: 'pretix'
      POSTGRES_DB: 'pretix'
  redis:
    image: 'redis:7'
    volumes:
      - 'redis-data:/data'

volumes:
  pretix-data:
  postgres-data:
  redis-data:
